#!/bin/python

# Begin imports
import os
import sys
import shutil

# Variable initialization
aur_packages = ["yay", "spotify"]
uname = os.getlogin()
repo-command = "repo-add custom.dp.tar.gz"

# Create custom repository
os.mkdir("/home/" + uname + "/cust_repo")
os.chdir("/home/" + uname + "/cust_repo")
for i in range(len(aur_packages)):
    os.system("git clone https://aur.archlinux.org/" + aur_packages[i] + ".git")
    os.chdir("./" + aur_packages[i])
    os.system("makepkg")
    os.chdir("..")
    shutil.move("./" + aur_packages[i] + "/" + aur_packages[i] + "*.zst ./")
    os.rmdir(aur_packages[i])
    repo-command += (" " + aur_packages[i] + "-*.zst")

os.system(repo-command)

# Build image
os.system("mkdir work")
os.system("sudo mkarchiso -w work -v -o ./ OS")

# Clean up system
os.system("rm -rf /home/" + uname + "/cust_repo")
