#!/bin/bash
echo "Devices: "
echo ""
lsblk
echo ""
read -p "What device do you want to install cscOS on: " device

img=$(ls | grep "cscOS-")
size=$(stat -c"%s" $img)
size=$((size/1048576))
read -p "Are you sure you would like to install cscOS to /dev/$device? The device will be wiped (Y/n)" yn
if (($yn == "n" || $yn == "N" || $yn == "no" || $yn == "No"))
then
  echo "cscOS installation aborted"
  exit 0
fi
echo "Flashing $img to /dev/$device, image size = $size MiB"
sudo dd if=$img of=/dev/$device status=progress
echo "Image flashed, finishing touches being applied"

sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | sudo fdisk /dev/$device
  n # new partition
  p # primary partition
  3 # partition number 3
    # default - start at beginning of disk 
    # default - start at beginning of disk 
  w # write partition
EOF

echo "Waiting for partition to finish being created"
sleep 10
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | sudo fdisk /dev/$device
  q # quit
EOF
device+="3"
while ! (lsblk | grep -q "$device")
do
  sleep 2.5
done
sudo mkfs.ext4 /dev/$device
echo "Bootable drive created"
exit 0
