#!/bin/bash
lsblk
read -p "What device do you want to install cscOS on: " device

img=$(ls | grep "cscOS-")
sudo dd if=$img of=/dev/$device

sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | sudo fdisk /dev/$device
  n # new partition
  p # primary partition
  3 # partition number 3
    # default - start at beginning of disk 
    # default - start at beginning of disk 
  w # write partition
EOF

echo "Waiting for partition to finish being created"
sleep 10
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | sudo fdisk /dev/$device
  q # quit
EOF
device+="3"
while ! (lsblk | grep -q "$device")
do
  sleep 2.5
done
sudo mkfs.ext4 /dev/$device
echo "Bootable drive created"
