# CMake generated Testfile for 
# Source directory: /home/bob/Git/calamares/src/libcalamares
# Build directory: /home/bob/Git/calamares/build/src/libcalamares
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(libcalamarestest "/home/bob/Git/calamares/build/libcalamarestest")
set_tests_properties(libcalamarestest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/bob/Git/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/bob/Git/calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;246;calamares_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresgeoiptest "/home/bob/Git/calamares/build/libcalamaresgeoiptest")
set_tests_properties(libcalamaresgeoiptest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/bob/Git/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/bob/Git/calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;248;calamares_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamareslocaletest "/home/bob/Git/calamares/build/libcalamareslocaletest")
set_tests_properties(libcalamareslocaletest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/bob/Git/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/bob/Git/calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;250;calamares_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresmodulesystemtest "/home/bob/Git/calamares/build/libcalamaresmodulesystemtest")
set_tests_properties(libcalamaresmodulesystemtest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/bob/Git/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/bob/Git/calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;252;calamares_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresnetworktest "/home/bob/Git/calamares/build/libcalamaresnetworktest")
set_tests_properties(libcalamaresnetworktest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/bob/Git/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/bob/Git/calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;254;calamares_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamarespackagestest "/home/bob/Git/calamares/build/libcalamarespackagestest")
set_tests_properties(libcalamarespackagestest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/bob/Git/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/bob/Git/calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;256;calamares_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamarespartitiontest "/home/bob/Git/calamares/build/libcalamarespartitiontest")
set_tests_properties(libcalamarespartitiontest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/bob/Git/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/bob/Git/calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;259;calamares_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamarespartitionkpmtest "/home/bob/Git/calamares/build/libcalamarespartitionkpmtest")
set_tests_properties(libcalamarespartitionkpmtest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/bob/Git/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/bob/Git/calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;260;calamares_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresutilstest "/home/bob/Git/calamares/build/libcalamaresutilstest")
set_tests_properties(libcalamaresutilstest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/bob/Git/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/bob/Git/calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;263;calamares_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;0;")
add_test(libcalamaresutilspathstest "/home/bob/Git/calamares/build/libcalamaresutilspathstest")
set_tests_properties(libcalamaresutilspathstest PROPERTIES  ENVIRONMENT "QT_PLUGIN_PATH=/home/bob/Git/calamares/build:" _BACKTRACE_TRIPLES "/usr/share/ECM/modules/ECMAddTests.cmake;96;add_test;/home/bob/Git/calamares/CMakeModules/CalamaresAddTest.cmake;32;ecm_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;265;calamares_add_test;/home/bob/Git/calamares/src/libcalamares/CMakeLists.txt;0;")
